### ISSUE TITLE
panic: unable to open database file: out of memory (14)

### ISSUE THREAD

**Issue by arsenicks** [andrewjjenkins/picsync#14]
Hi,

I'm trying to list the app Id for the google photo album and I get this:

picsync googlephotos list
panic: unable to open database file: out of memory (14)

```
goroutine 1 [running]:
main.runGooglephotosList(0x13c0180, {0x13fc228, 0x0, 0x0})
	/home/arsenick/code/picsync/cmd/picsync/googlephotos.go:146 +0x67b
github.com/spf13/cobra.(*Command).execute(0x13c0180, {0x13fc228, 0x0, 0x0})
	/home/arsenick/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x827
github.com/spf13/cobra.(*Command).ExecuteC(0x13bf320)
	/home/arsenick/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3cd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/arsenick/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/arsenick/code/picsync/cmd/picsync/main.go:41 +0x25
```

picsync built with the latest version from master branch.
go version go1.17.13 linux/amd64

Let me know if you need anything else!

Thanks for sharing your work!!

**Comment by arsenicks** [comment]
Will close this because it's now fixed but this comment might help others.

This error doesn't necessary mean there's not enough memory, in my case the problem was the user I was using to run the picsync command didn't had the correct permission to write, so picsync tried to create the picsync-metadata-cache.db but wasn't able to do, resulting in this error.

fixing the permission in the current directory fixed the problem.
